### ISSUE TITLE
The name "rest" is completely impossible to google.

### ISSUE THREAD

**Issue by lpil** [silkapp/rest#105]
Hello!

Rest is a really poor name for anything in the web world. It's impossible to find information about this project as any search with "rest" and "haskell" gives you results to do with REST for every other Haskell framework and Haskell library out there.

Cheers,
Louis

**Comment by bergmark** [comment]
7/10 of the first search results for "haskell rest" on google are for this project, so it doesn't seem like a big problem to me. I think at this point it would be even harder to find information about the project if we changed the name.

If you want a challenge try googling things related to Go or Flow :-)

**Comment by lpil** [comment]
> If you want a challenge try googling things related to Go or Flow :-)

Or Hack. Jeeze.

**Comment by bergmark** [comment]
We won't change this now, but thank's for showing interest in the project.
