### ISSUE TITLE
Remove 'Show' constraint from 'ReadId' constructor in 'Ident'

### ISSUE THREAD

**Issue by hesselink** [silkapp/rest#118]
I think we can remove the `Show id` constraint in [the `ReadId` constructor of `Ident`](https://github.com/silkapp/rest/blob/f1937606ee5bb246e900b182a522199cd7505940/rest-core/src/Rest/Dictionary/Types.hs#L89). I removed it and nothing seems to break. I also don't remember why we have it. @bergmark Do you remember why we have this?

**Comment by bergmark** [comment]
Nope...

**Comment by hesselink** [comment]
Hmm, then I guess after a last look at the history we should just remove it.
