### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by coubeatczech** [silkapp/rest#124]
on 60faa55887fbf7332dc7aa82a9505e2d92f7c316 ,

the build fails with compile fail in [network](https://github.com/haskell/network/issues/60) dependency.

Explicitly specifying the `network == 2.4.0.1` in `rest-core.cabal` will make the build compile.

On
GHC `7.6.3`

**Comment by hesselink** [comment]
What is the error message?

**Comment by coubeatczech** [comment]
Sorry for my poor linking abilities, now the link to network issue works, the error is exactly the same as there.

**Comment by hesselink** [comment]
That looks like a problem with network and not rest, right? If I read it correctly, we (a trustee or network maintainer) could change the parsec bounds on network 2.4.0.0 to require parsec 3.

**Comment by coubeatczech** [comment]
Yes, the compile error is happening during compilation of this particular dependency, not during compilation any of rest-* itself, therefore the fix should probably just involve changing some versions in cabal's dependency list.

**Comment by hesselink** [comment]
OK, then I'll close this issue and see if we can fix it with network instead.

**Comment by hesselink** [comment]
The network issue should be gone now. Can you check if it now picks the right dependencies (after a `cabal update`)?

**Comment by coubeatczech** [comment]
Now I get this for installation in a fresh sandbox:

cabal: Could not resolve dependencies:
trying: rest-stringmap-0.2.0.6 (user goal)
trying: base-4.6.0.1/installed-8aa... (dependency of rest-stringmap-0.2.0.6)
trying: tostring-0.2.1.1 (dependency of rest-stringmap-0.2.0.6)
trying: utf8-string-1 (dependency of tostring-0.2.1.1)
trying: rest-gen-0.17.0.5 (user goal)
next goal: HStringTemplate (dependency of rest-gen-0.17.0.5)
rejecting: HStringTemplate-0.8.3, 0.8.2 (conflict:
time==1.4.0.1/installed-10d..., HStringTemplate => time>=1.4.2 && <1.6)
rejecting: HStringTemplate-0.8.1, 0.8 (conflict:
time==1.4.0.1/installed-10d..., HStringTemplate => time>=1.5 && <1.6)
rejecting: HStringTemplate-0.7.3, 0.7.1, 0.7.0 (conflict: utf8-string==1,
HStringTemplate => utf8-string<1)
trying: HStringTemplate-0.6.12
Backjump limit reached (change with --max-backjumps)

**Comment by hesselink** [comment]
Can you post the exact page(s) you're installing, the cabal output with `-v`, and the versions of ghc and cabal you're using? I can install `rest-core` in a fresh sandbox using ghc 7.6.3 and cabal-install 1.22.4.0. Here is the full install plan:

```
In order, the following would be installed:
byteable-0.1.1 (via: cryptohash-0.11.6) (new package)
cryptohash-0.11.6 (via: uuid-1.3.10) (new package)
dlist-0.7.1.1 (via: aeson-0.7.0.6) (new package)
generic-deriving-1.7.0 (via: json-schema-0.7.3.6 generic-aeson-0.2.0.6 generic-xmlpickler-0.1.0.2) (new package)
hashable-1.2.3.2 (via: uuid-types-1.0.1 rest-stringmap-0.2.0.6 aeson-0.7.0.6 unordered-containers-0.2.5.1 scientific-0.3.3.8 case-insensitive-1.2.0.4) (new version)
case-insensitive-1.2.0.4 (via: rest-core-0.36.0.4 rest-types-1.14.0.1 tostring-0.2.1.1) (new version)
hxt-charproperties-9.2.0.1 (via: hxt-9.3.1.15 hxt-regex-xmlschema-9.2.0.2 hxt-unicode-9.0.2.4) (new package)
hxt-unicode-9.0.2.4 (via: hxt-9.3.1.15) (new package)
network-info-0.2.0.6 (via: uuid-1.3.10) (new package)
safe-0.3.9 (via: rest-core-0.36.0.4 errors-2.0.0) (new package)
scientific-0.3.3.8 (via: json-schema-0.7.3.6 aeson-utils-0.3.0.2 aeson-0.7.0.6 attoparsec-0.11.3.4) (new package)
attoparsec-0.11.3.4 (latest: 0.13.0.0) (via: generic-aeson-0.2.0.6 aeson-utils-0.3.0.2 aeson-0.7.0.6) (new version)
tagged-0.8.0.1 (via: rest-stringmap-0.2.0.6 json-schema-0.7.3.6 generic-aeson-0.2.0.6) (new package)
transformers-0.4.3.0 (via: rest-core-0.36.0.4 transformers-compat-0.4.0.4 fclabels-2.0.2.2 mtl-2.2.1 errors-2.0.0) (new version)
errors-2.0.0 (via: rest-core-0.36.0.4) (new package)
mtl-2.2.1 (via: rest-core-0.36.0.4 json-schema-0.7.3.6 generic-aeson-0.2.0.6 aeson-0.7.0.6 hxt-pickle-utils-0.1.0.3 hxt-9.3.1.15 parsec-3.1.9 mtl-compat-0.2.1.3 fclabels-2.0.2.2) (new version)
fclabels-2.0.2.2 (via: rest-core-0.36.0.4) (new package)
mtl-compat-0.2.1.3 (via: rest-core-0.36.0.4) (new package)
parsec-3.1.9 (via: network-uri-2.6.0.3 hxt-9.3.1.15 network-2.5.0.0 multipart-0.1.2 hxt-regex-xmlschema-9.2.0.2) (new version)
hxt-regex-xmlschema-9.2.0.2 (via: hxt-9.3.1.15) (new package)
multipart-0.1.2 (via: rest-core-0.36.0.4) (new package)
network-2.5.0.0 (latest: 2.6.2.0) (via: hxt-9.3.1.15) (new version)
hxt-9.3.1.15 (via: rest-core-0.36.0.4 rest-types-1.14.0.1 rest-stringmap-0.2.0.6 hxt-pickle-utils-0.1.0.3 generic-xmlpickler-0.1.0.2) (new package)
generic-xmlpickler-0.1.0.2 (via: rest-types-1.14.0.1) (new package)
hxt-pickle-utils-0.1.0.3 (via: rest-core-0.36.0.4) (new package)
network-uri-2.6.0.3 (via: uri-encode-1.5.0.4) (new package)
transformers-compat-0.4.0.4 (via: rest-core-0.36.0.4) (new package)
unordered-containers-0.2.5.1 (via: rest-core-0.36.0.4 rest-stringmap-0.2.0.6 json-schema-0.7.3.6 generic-aeson-0.2.0.6 aeson-0.7.0.6) (new version)
aeson-0.7.0.6 (latest: 0.9.0.1) (via: rest-core-0.36.0.4 rest-types-1.14.0.1 rest-stringmap-0.2.0.6 json-schema-0.7.3.6 generic-aeson-0.2.0.6 aeson-utils-0.3.0.2) (new package)
aeson-utils-0.3.0.2 (via: rest-core-0.36.0.4) (new package)
generic-aeson-0.2.0.6 (via: rest-types-1.14.0.1 json-schema-0.7.3.6) (new package)
json-schema-0.7.3.6 (via: rest-core-0.36.0.4 rest-types-1.14.0.1 rest-stringmap-0.2.0.6) (new package)
utf8-string-1 (via: rest-core-0.36.0.4 uri-encode-1.5.0.4 tostring-0.2.1.1) (new package)
tostring-0.2.1.1 (via: rest-stringmap-0.2.0.6) (new package)
rest-stringmap-0.2.0.6 (via: rest-core-0.36.0.4 rest-types-1.14.0.1) (new package)
uri-encode-1.5.0.4 (via: rest-core-0.36.0.4) (new package)
uuid-types-1.0.1 (via: uuid-1.3.10) (new package)
uuid-1.3.10 (via: rest-core-0.36.0.4 rest-types-1.14.0.1) (new package)
rest-types-1.14.0.1 (via: rest-core-0.36.0.4) (new package)
rest-core-0.36.0.4 (new package)
```

**Comment by bergmark** [comment]
The suggestion in the message, to increase the backjump limit with --max-backjumps (-1 for unlimited) will solve your problem or give the actual error. Combining that with --reorder-goals usually helps to find a (complicated) solution quicker.  Older versions of cabal have bugs when --reorder-goals isn't used




HTH

**Comment by coubeatczech** [comment]
Ok, so I added the line 

    CABAL_FLAGS=--max-backjumps=-1 --reorder-goals

into the `Makefile`, now I can build it with `make all`. Thanks!
