### ISSUE TITLE
Misleading documentation at fileO

### ISSUE THREAD

**Issue by coubeatczech** [silkapp/rest#130]
It would be nice to correct / make clearer the documentation on this line:

https://github.com/silkapp/rest/blob/4eefbf539185b73bc441924876c6cf1b2800602e/rest-core/src/Rest/Dictionary/Combinators.hs#L148

At least I tried to put there the combination of a ByteString and "image/jpeg" with the hope that it would use the latter for mime/type whereas it uses it for file name.

**Comment by hesselink** [comment]
Thanks for reporting! That comment has been wrong for a long time...

**Comment by hesselink** [comment]
Released as rest-core 0.36.0.5.
