### ISSUE TITLE
Reserved keywords in javascript

### ISSUE THREAD

**Issue by jumi99** [silkapp/rest#140]
There are reserved keywords in javascript that, depending on the parser, cannot be used as identifiers.
For example "export" is a reserved keyword and the default browser in android 2.3 will refuse to parse any javascript that uses export as an identifier.
It would be nice if rest-gen could rename them when generating code, or at least give an error.

**Comment by bergmark** [comment]
Do you have a decent list of names to replace?

**Comment by hesselink** [comment]
There's a list [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Lexical_grammar#Keywords), for example.

**Comment by bergmark** [comment]
> The following are reserved as future keywords by older ECMAScript specifications

**Comment by hesselink** [comment]
Fixed in https://github.com/silkapp/rest/commit/6e9d1d92cce09810f165688303ce0b20d96be94d.
