### ISSUE TITLE
REST tutorial website: wrong Hackage link for rest-snap

### ISSUE THREAD

**Issue by privong** [silkapp/rest#153]
I couldn't find a repo for the "[Tutorial - Writing a simple REST API](https://silkapp.github.io/rest/tutorial.html)", so opening an issue here...
In the "Running It" section, both the "rest-happstack" and "rest-snap" links to go the rest-happstack driver. The latter should go to https://hackage.haskell.org/package/rest-snap

**Comment by hesselink** [comment]
Thanks, fixed! For future reference, the tutorial/website lives on the gh-pages branch in this repo.

**Comment by privong** [comment]
@hesselink Ah, right. I'd forgotten how gh-pages worked. Thanks for the reminder.
