### ISSUE TITLE
Is it possible to follow HATEOAS?

### ISSUE THREAD

**Issue by pierre-thierry** [silkapp/rest#159]
I don't see in the tutorial a way to represent an actual REST API, using HATEOAS, is it documented elsewhere?

**Comment by hesselink** [comment]
What kind of things are you looking for, exactly?

**Comment by pierre-thierry** [comment]
The guiding principle of REST is that URIs are not known and built by the client, but gathered throught hypermedia links, and you follow those links to change state. That's REpresentational State Transfer.

But in the tutorial, I only see the non-REST way of defining a client, through known URI.

I'd like a way to describe how links for state transfers are gathered in the representation of a resource.

**Comment by hesselink** [comment]
No, that currently doesn't exist. It should be possible to add it though, since the API definitions allow introspection.

**Comment by pierre-thierry** [comment]
Why call the library "rest" if it cannot describe REST APIs?
