### ISSUE TITLE
rest-wai?: [Feature Req] Add ability to better control API versioning

### ISSUE THREAD

**Issue by orclev** [silkapp/rest#52]
The current implementation is **very** opinionated about the way APIs should be versioned, it would be nice to provide a bit more flexibility for this. In particular I favor selecting API version via HTTP Header rather than including it in the URL. It seems like all the building blocks are there for the most part, rest-wai just needs to expose a more flexible function for converting an API instance into a Application.

Additionally even if you do decide to include the version in the URL I don't see an easy way to change the version format or location. E.G. I can't make my URL look like "/api/v1/someResource", I'm forced into using "/1.0/api/someResource".

I would suggest something along the lines of:

```apiWithVersionToApplication :: Run m IO -> Api m -> (RestInput -> Version) -> Application```

with the expectation that it would then use the returned version from the lookup function when routing. I'd also expect there would most likely be a modified version of ```apiToHandler'``` that would similarly either accept a version or else use the lookup function from the previously mentioned function.

**Comment by L8D** [comment]
I would want to add that the versioning in rest is very opinionated and IMO completely useless for most situations. Unless you publish/track each release of your package under a separate name (and keep all the dependency versions compatible across every version) there's no way to actually provide each version of the entire API server implementation. The most you can do is apply versioning to different route configurations, which is understandable but in general pretty useless when you can't distinguish between versions of individual resources.

In general I think the versioning system here should be entirely opt-in, as I'd prefer to handle versioning externally (via headers, proxies, separate domains, etc.).

**Comment by hesselink** [comment]
The current scheme is definitely workable as it's the one we use at Silk :) However, I'm perfectly happy to accept functionality that allows other ways of versioning, or no versioning. If anyone wants to work on this, let me know and I can help you around the code base.

**Comment by L8D** [comment]
@hesselink still compiling and setting up GHC and tools atm. In the next week I hope I can get down and hack around with the repo and basically make versioning opt-in. Just from reading the code, I'm guessing it'll come down to changing [this function](https://github.com/silkapp/rest/blob/82fede7eaea54c738a43eefdc4d32bc4d74059dd/rest-core/src/Rest/Driver/Routing/Internal.hs#L83) and the underlying definition of `Api` to look like `Single (Some1 (Router m)) | Versioned [(Version, Some1 (Router m))]` or something.

**Comment by hesselink** [comment]
Yes, that sounds good. Then in `Rest.Driver.Routing.Internal` the `routeWith` function needs to be changed, since it now always expects a version. It takes an `Api`, so it should probably just pattern match and skip the version check for `Single`.

**Comment by L8D** [comment]
@hesselink So I've gotten the changes implemented locally, ready to commit. The first package that fails to build is rest-gen (because it looks up versions). I'm not sure how I should handle configuration in that case. My options are to make the `apiVersion` an optional configuration option, that `generate` will default to `"latest"` when `Api` is `Versioned` or just selecting the single version when `Api` is `Unversioned`. I can also just leave the apiVersion option in there, and have `generate` ignore it whenever the api is unversioned.

**Comment by hesselink** [comment]
@L8D Good to hear! As for rest-gen's command line options, it looks like `apiVersion` is already optional, and defaults to "latest". I would say that if you have an unversioned api, "latest" should match and anything else should throw an error. The behavior for versioned apis shouldn't change. Does that make sense, or am I misunderstanding the problem?
