### ISSUE TITLE
Inconsistencies in error handling between backends

### ISSUE THREAD

**Issue by bergmark** [silkapp/rest#61]
If you have a handler whose body contains say `error "foo"` all backends handle this differently and only rest-wai does the appropriate thing.

* `rest-happstack` doesn't print the error, the HTTP response is html saying "Something went wrong"
* `rest-snap` doesn't print the error, the HTTP response is text containing the error message
* `rest-wai` prints the error, the HTTP response is text saying "Something went wrong"

All backends should print the error, it may be less important that the response is the same, but showing the actual error message like `rest-snap` does is bad.

**Comment by bergmark** [comment]
Is there anything we can actually do about this in rest? It sounds to me that users just have to pick a backend that does this properly. We can probably close this.

**Comment by hesselink** [comment]
We could switch `rest` to use some kind of streaming abstraction (pipes, conduit, io-streams). Then I think `wai` and `snap` could handle this correctly. I'm not sure how much work this would be. A lot of it would just be choosing what to use and seeing how it impacts the whole framework, I guess.

**Comment by bergmark** [comment]
wai already does this well enough, and snap-1.0 should also fix it.

**Comment by hesselink** [comment]
OK, let's close it then.
