### ISSUE TITLE
HTTP headers ought to be treated as case insensitive 

### ISSUE THREAD

**Issue by tathougies** [silkapp/rest#71]
`rest` currently parses HTTP headers as case sensitive. The HTTP standard says that they ought to be treated case insensitive. This is especially a problem because the Node.js javascript generated by rest-gen sends the header "Content-type" for POST requests and `Rest.Driver.Perform` calls `getHeader "Content-Type"`. This means that the Javascript client library generated by rest-gen doesn't actually work with the API when serving the API via WAI and Warp.

This may not affect the Happstack and Snap backends because they call the underlying server's `getHeader` function which treats header names correctly.

One solution would be to change the type of `RestInput.headers` to `HashMap (CI String) String` in `Rest.Driver.RestM`

**Comment by pikeas** [comment]
If pull request #72 was merged, why is this issue still open?

**Comment by hesselink** [comment]
Because we didn't close it? ;) Thanks for drawing our attention to it.
