### ISSUE TITLE
Use ExceptT instead of ErrorT

### ISSUE THREAD

**Issue by jcpetruzza** [silkapp/rest#78]
`ErrorT` was deprecated in `transformers-0.4` in favor of `ExceptT`, so one gets a lot of deprecation warnings when writing rest handlers with a newer version of `transformers`. There is a package `transformers-compat` that backports `ExceptT` to `transformers-0.3`, which could be used to remain compatible with previous versions.

**Comment by jcpetruzza** [comment]
There is now a [mtl-compat](https://github.com/RyanGlScott/mtl-compat) package that could be used for this.

**Comment by bergmark** [comment]
I just saw that :-)

I'm +1 on changing this now.

**Comment by bergmark** [comment]
I attempted this but some of our dependencies need to be updated too. I'll send some PRs

**Comment by bergmark** [comment]
https://www.haskell.org/pipermail/haskell-cafe/2015-February/118037.html

**Comment by bergmark** [comment]
I may have jumped the gun on this a bit with #104. There are also libraries that rest-core depends on that have this issue. I think it can be worked around, but it may not be worth switching before they have been updated.

**Comment by hesselink** [comment]
Another issue might be that people *using* rest might be running into this issue, making it impossible for them to use `ExceptT` and thus rest.

**Comment by bergmark** [comment]
OTOH it might be good for us to do this anyway so these packages surface and can be fixed :-)

But i'll at least hold off on this until our direct dependecies are fixed.

https://github.com/fpco/stackage/issues/439

**Comment by bergmark** [comment]
I have sent pull requests that fixes this to all packages included in stackage, if they all get merged I think that should be good enough.

**Comment by bergmark** [comment]
Fixed
